{
 "exception": "Destination path '/usr/share/miniconda/envs/run_env/conda-bld/root_1610123508035/work/root-source/roofit/roofit' already exists",
 "traceback": [
  "Traceback (most recent call last):",
  "  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/audit.py\", line 480, in main",
  "    deps = v[\"run\"](fctx, ctx)",
  "  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/audit.py\", line 106, in depfinder_audit_feedstock",
  "    return extract_deps_from_source(recipe_dir)",
  "  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/audit.py\", line 84, in extract_deps_from_source",
  "    cb_work_dir = _get_source_code(recipe_dir)",
  "  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py\", line 640, in _get_source_code",
  "    return provide(md)",
  "  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/conda_build/source.py\", line 860, in provide",
  "    unpack(source_dict, src_dir, metadata.config.src_cache, recipe_path=metadata.path,",
  "  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/conda_build/source.py\", line 169, in unpack",
  "    shutil.move(os.path.join(tmpdir, f), os.path.join(src_dir, f))",
  "  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/shutil.py\", line 786, in move",
  "    raise Error(\"Destination path '%s' already exists\" % real_dst)",
  "shutil.Error: Destination path '/usr/share/miniconda/envs/run_env/conda-bld/root_1610123508035/work/root-source/roofit/roofit' already exists",
  ""
 ]
}