{
  "done": [
    "basemap",
    "librttopo",
    "libspatialite",
    "gdal",
    "shapely",
    "cartopy",
    "r-rgeos"
  ],
  "in-pr": [
    "pygeos",
    "pdal",
    "omniscidb"
  ],
  "awaiting-pr": [],
  "not-solvable": [
    "r-terra",
    "postgis"
  ],
  "awaiting-parents": [
    "r-exactextractr",
    "pyogrio",
    "qgis"
  ],
  "bot-error": [],
  "_feedstock_status": {
    "basemap": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/basemap-feedstock/pull/83",
      "pr_status": "clean"
    },
    "cartopy": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/cartopy-feedstock/pull/128",
      "pr_status": "unknown"
    },
    "gdal": {
      "num_descendants": 9,
      "immediate_children": [
        "omniscidb",
        "pdal",
        "postgis",
        "pyogrio",
        "qgis",
        "r-exactextractr",
        "r-terra",
        "rsgislib",
        "spdlib"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/gdal-feedstock/pull/550",
      "pr_status": "unknown"
    },
    "libspatialite": {
      "num_descendants": 11,
      "immediate_children": [
        "gdal",
        "libgdal",
        "qgis"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/libspatialite-feedstock",
      "pr_status": null
    },
    "postgis": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1404009947\">bot CI job</a>): master: ['osx_64_: Encountered problems while solving:\\n  - package libgdal-3.3.0-h27e2542_1 requires geos >=3.9.1,<3.9.2.0a0, but none of the providers can be installed\\n']"
    },
    "qgis": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "shapely": {
      "num_descendants": 1,
      "immediate_children": [
        "cartopy"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/shapely-feedstock/pull/90",
      "pr_status": "unknown"
    },
    "r-rgeos": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/r-rgeos-feedstock/pull/29",
      "pr_status": "unknown"
    },
    "pdal": {
      "num_descendants": 1,
      "immediate_children": [
        "qgis"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/pdal-feedstock/pull/143",
      "pr_status": "unknown"
    },
    "pygeos": {
      "num_descendants": 1,
      "immediate_children": [
        "pyogrio"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/pygeos-feedstock/pull/44",
      "pr_status": "unstable"
    },
    "r-exactextractr": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "omniscidb": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/omniscidb-feedstock/pull/62",
      "pr_status": "clean"
    },
    "pyogrio": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "librttopo": {
      "num_descendants": 12,
      "immediate_children": [
        "libspatialite"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/librttopo-feedstock/pull/10",
      "pr_status": "unknown"
    },
    "r-terra": {
      "num_descendants": 1,
      "immediate_children": [
        "r-exactextractr"
      ],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1404206622\">bot CI job</a>): master: ['linux_aarch64_r_base4.0: Encountered problems while solving:\\n  - package libgdal-3.3.0-h14e8861_1 requires geos >=3.9.1,<3.9.2.0a0, but none of the providers can be installed\\n', 'linux_aarch64_r_base4.1: Encountered problems while solving:\\n  - package libgdal-3.3.0-h14e8861_1 requires geos >=3.9.1,<3.9.2.0a0, but none of the providers can be installed\\n', 'linux_ppc64le_r_base4.0: Encountered problems while solving:\\n  - package libgdal-3.3.0-h572fad7_0 requires geos >=3.9.1,<3.9.2.0a0, but none of the providers can be installed\\n', 'linux_ppc64le_r_base4.1: Encountered problems while solving:\\n  - package libgdal-3.3.0-h572fad7_0 requires geos >=3.9.1,<3.9.2.0a0, but none of the providers can be installed\\n']"
    }
  }
}